name: client
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  email_validator: ^2.1.17
  provider: ^6.0.5
  flutter_profile_picture: ^2.0.0
  intl: ^0.18.1
  syncfusion_flutter_calendar: ^22.1.39
  shared_preferences: ^2.2.0
  dio: ^5.3.0
  google_fonts: ^4.0.4
  fluttertoast: ^8.2.2
  loading_animation_widget: ^1.2.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
